const presente = [
  "Ich beeile mich, damit ich pünktlich ankomme.", "Mi sbrigo per arrivare puntuale.", 
  "Sie interessiert sich sehr für moderne Kunst.", "Lei è molto interessata all'arte moderna.", 
  "Wir freuen uns darauf, dich wiederzusehen.", "Siamo contenti di rivederti.", 
  "Ich erinnere mich nicht mehr an seinen Namen.", "Non ricordo più il suo nome.", 
  "Du solltest mehr Obst essen.", "Dovresti mangiare più frutta.", 
  "Sie arbeitet als Übersetzerin.", "Lei lavora come traduttrice. ", 
  "Ich habe seit Tagen nichts von ihm gehört.", "Non ho sue notizie da giorni.",
  "Wir treffen uns jeden Freitagabend.", "Ci incontriamo ogni venerdì sera.", 
  "Er gibt mir Nachhilfe in Mathe.", "Mi dà ripetizioni di matematica.", 
  "Ich kann mich auf dich verlassen.", "Posso contare su di te.", 
  "Sie beschwert sich oft über Kleinigkeiten.", "Si lamenta spesso per sciocchezze.", 
  "Wir fahren nächste Woche nach Berlin.", "La settimana prossima andiamo a Berlino.", 
  "Er erledigt seine Aufgaben schnell und gründlich.", "Svolge i suoi compiti rapidamente e accuratamente.",
  "Ich bleibe heute Abend zu Hause.", "Stasera resto a casa.", 
  "Sie arbeitet seit vielen Jahren als Lehrerin.", "Lavora da molti anni come insegnante.", 
  "Wir treffen uns morgen um 10 Uhr.", "Ci vediamo domani alle 10.",
  "Er nimmt seit einem Jahr Gitarrenunterricht.", "Da un anno prende lezioni di chitarra.",
  "Ich finde Mathematik sehr interessant.", "Trovo la matematica molto interessante.", 
  "Sie hat die Stadt nach dem Studium verlassen.", "Ha lasciato la città dopo l'università.",
  "Wir wandern am Wochenende in den Bergen.", "Facciamo trekking in montagna nel weekend.", 
  "Er isst jeden Tag drei Portionen Gemüse.", "Mangia tre porzioni di verdura al giorno.", 
  "Ich gehe heute schwimmen.", "Oggi vado a nuotare.", 
  "Sie spricht sehr gut Französisch.", "Parla molto bene il francese.", 
  "Wir sehen uns am Freitag um 20 Uhr.", "Ci vediamo venerdì alle 20.",
  "Er trainiert für den Marathonlauf.", "Si allena per la maratona.", 
  "Ich lese die Zeitung jeden Morgen beim Frühstück.", "Leggo il giornale ogni mattina a colazione.",
  "Dieses medizinische Gerät ist sehr fortschrittlich.", "Questo apparecchio medico è molto avanzato.",
  "Sein Verhalten ist äußerst unangemessen.", "Il suo comportamento è estremamente inappropriato.",
  "Sie führt ein außerordentlich stressiges Leben.", "Lei conduce una vita estremamente stressante.",
  "Diese Angelegenheit ist äußerst dringend.", "Questa faccenda è estremamente urgente.",
  "Ihre Musikauswahl ist ziemlich avantgardistisch.", "La sua scelta musicale è piuttosto avanguardistica.",
  "Die Lage der Umwelt ist zunehmend alarmierend.", "La situazione ambientale è sempre più allarmante.",
  "Er hat eine unglaublich positive Einstellung.", "Lui ha un atteggiamento incredibilmente positivo.",
  "Ihr Stil ist avantgardistisch und einzigartig.", "Il suo stile è avanguardistico e unico.",
  "Sein Vermögen ist beträchtlich angewachsen.", "La sua ricchezza è cresciuta considerevolmente.",
  "Diese Angelegenheit ist äußerst kompliziert.", "Questa faccenda è estremamente complicata.",
  "Ihre Arbeit ist außergewöhnlich präzise.", "Il suo lavoro è straordinariamente preciso.",
  "Er ist ein unglaublich talentierter Musiker.", "Lui è un musicista incredibilmente talentuoso.",
  "Dieses Kunstwerk ist avantgardistisch und provokativ.", "Quest'opera d'arte è avanguardistica e provocatoria.",
  "Ihr Stil ist sehr extravagant.", "Il suo stile è molto stravagante.",
  "Seine Geschäftsidee ist außerordentlich innovativ.", "La sua idea imprenditoriale è estremamente innovativa.",
  "Sie ist eine unglaublich kreative Person.", "Lei è una persona incredibilmente creativa.",
  "Sein Verhalten war äußerst rücksichtslos.", "Il suo comportamento è stato estremamente sconsiderato.",
  "Ihre Fähigkeiten sind außergewöhnlich beeindruckend.", "Le sue capacità sono straordinariamente impressionanti.",
  "Er hat einen sehr exzentrischen Kleidungsstil.", "Ha uno stile molto eccentrico.",
  "Diese Regelung ist überaus restriktiv.", "Questo regolamento è estremamente restrittivo.",
  "Sie ist eine ungewöhnlich talentierte Malerin.", "Lei è una pittrice insolitamente talentuosa.",
  "Seine Ansichten sind ziemlich provokant.", "Le sue opinioni sono alquanto provocatorie.",
  "Ihr Stil ist avantgardistisch und mutig.", "Il suo stile è avanguardistico e audace.",
  "Dieses Abkommen ist äußerst vorteilhaft.", "Questo accordo è estremamente vantaggioso."
]

const imprefetto = [
  "Als Kind spielte ich jeden Tag im Garten.", "Da bambino giocavo ogni giorno in giardino.", 
  "Letzten Sommer machten wir eine Rundreise durch Italien.", "L'estate scorsa facemmo un giro dell'Italia.", 
  "Ich wusste nie, was ich nach der Schule machen wollte.", "Non ho mai saputo cosa volevo fare dopo la scuola.", 
  "In meiner Jugend interessierte ich mich für Literatur.", "Da giovane mi interessavo di letteratura.", 
  "Während des Studiums jobbte ich in einer Bar.", "Quando studiavo facevo lavoretti in un bar.",
  "Als ich jünger war, rauchte ich.", "Quando ero più giovane, fumavo.", 
  "In meiner Kindheit besuchte ich oft meine Großeltern.", "Da bambino andavo spesso a trovare i miei nonni.",
  "Letzten Winter schneite es ungewöhnlich viel.", "L'inverno scorso nevicò insolitamente tanto.", 
  "Früher trank ich mehr Kaffee als heute.", "Una volta bevevo più caffè di adesso.", 
  "In meinen Zwanzigern ging ich oft feiern.", "Quando avevo vent'anni uscivo spesso a divertirmi.", 
  "Während meines Auslandsjahrs reiste ich viel.", "Durante l'anno all'estero viaggiavo molto.",
  "Als Student hatte ich wenig Geld.", "Quando ero studente avevo pochi soldi.",
  "In meiner Jugend hörte ich oft klassische Musik.", "Da giovane ascoltavo spesso musica classica.",
  "Letztes Jahr lief mein Studium sehr stressig.", "L'anno scorso l'università era molto stressante.", 
  "Früher ritt ich regelmäßig.", "Una volta andavo a cavallo regolarmente.", 
  "Als Kind fuhr ich Ski in den Alpen.", "Da bambino sciavo sulle Alpi.", 
  "Während meiner Ausbildung arbeitete ich hart.", "Durante la mia formazione lavoravo duramente.", 
  "In meinen Zwanzigern reiste ich viel per Anhalter.", "Nei miei vent'anni viaggiavo molto facendo l'autostop.", 
  "Letzten Sommer war es außergewöhnlich heiß.", "L'estate scorsa faceva insolitamente caldo.", 
  "Früher rauchte ich mehr als heute.", "Una volta fumavo di più rispetto ad ora.", 
  "Als Studentin jobbte ich in einer Bäckerei.", "Quando studiavo, lavoravo in una panetteria.", 
  "Während meines Auslandsaufenthalts vermisste ich meine Familie.", "Quando ero all'estero sentivo la mancanza della mia famiglia.",
  "In meiner Jugend war ich sehr abenteuerlustig.","Da giovane ero molto avventuroso.",
  "Früher war ich ziemlich waghalsig.","Una volta ero piuttosto temerario.",
  "Als Kind war ich äußerst schüchtern.","Da bambino ero estremamente timido.",
  "Während der Schulzeit war ich sehr ehrgeizig.","Quando andavo a scuola ero molto ambizioso.",
  "In meinen Zwanzigern war ich sehr spontan.","Nei miei vent'anni ero molto estemporaneo.",
  "Früher war ich sehr empfindsam.","Una volta ero molto sensibile.",
  "Als Jugendliche war ich recht rebellisch.","Da adolescente ero piuttosto ribelle.",
  "In meiner Kindheit war ich unglaublich naiv.","Durante l'infanzia ero incredibilmente ingenuo.",
  "Während meiner Ausbildung war ich äußerst fleißig.","Durante la mia formazione ero estremamente diligente.",
  "In meiner Jugend war ich ziemlich unbekümmert.","Da giovane ero piuttosto spensierato.",
  "Früher war ich sehr gedankenverloren.","Una volta ero molto distratto.",
  "Als Student war ich äußerst diszipliniert.","Quando studiavo ero estremamente disciplinato.",
  "In meinen Zwanzigern war ich sehr draufgängerisch.","Nei miei vent'anni ero molto temerario.",
  "Während meines Auslandsjahrs war ich sehr abenteuerlustig.","Durante l'anno all'estero ero molto avventuroso.",
  "Als Teenager war ich äußerst rebellisch.","Da adolescente ero estremamente ribelle.",
  "In meiner Jugend war ich sehr unvorsichtig.","Da giovane ero molto incauto.",
  "Früher war ich sehr verträumt.","Una volta ero molto sognatore.",
  "Während meiner Schulzeit war ich ziemlich schüchtern.","Quando andavo a scuola ero abbastanza timido.",
  "In meinen Zwanzigern war ich äußerst unbekümmert.","Nei miei vent'anni ero estremamente spensierato.",
  "Als Studentin war ich sehr idealistisch.","Quando studiavo ero molto idealista.",
  "In meiner Jugend war ich äußerst empfindsam.","Da giovane ero estremamente sensibile.",
  "Früher war ich sehr phantasievoll.","Una volta ero molto fantasioso.",
  "Während meines Studiums war ich ziemlich zielstrebig.","Durante l'università ero abbastanza determinato.",
  "In meiner Kindheit war ich sehr scheu.","Durante l'infanzia ero molto timido."
]

const passatoProssimo = [
  "Ich habe gestern viel gelernt.", "Ieri ho studiato molto.",
  "Wir sind letzte Woche nach Italien gereist.", "La settimana scorsa siamo andati in Italia.",
  "Hast du das Buch schon gelesen?", "Hai già letto il libro?",
  "Ich habe meine Freunde angerufen.", "Ho telefonato ai miei amici.",
  "Sie hat mir ein Geschenk mitgebracht.", "Lei mi ha portato un regalo.",
  "Wir haben uns im Park getroffen.", "Ci siamo incontrati al parco.",
  "Ich habe die Prüfung bestanden.", "Ho superato l'esame.",
  "Er hat mir geholfen.", "Lui mi ha aiutato.",
  "Wir haben zusammen gelacht.", "Abbiamo riso insieme.",
  "Sie hat die Blumen gegossen.", "Lei ha innaffiato i fiori.",
  "Ich habe die Nachricht bekommen.", "Ho ricevuto il messaggio.",
  "Er hat gut geschlafen.", "Lui ha dormito bene.",
  "Wir haben uns verlaufen.", "Ci siamo persi.",
  "Sie haben sich gestritten.", "Loro hanno litigato.",
  "Ich habe die Rechnung bezahlt.", "Ho pagato il conto.",
  "Er hat den Zug verpasst.", "Lui ha perso il treno.",
  "Wir haben im Garten gearbeitet.", "Abbiamo lavorato in giardino.",
  "Sie hat sich verletzt.", "Lei si è fatta male.",
  "Ich habe die Katze gestreichelt.", "Ho accarezzato il gatto.",
  "Er hat mir ein Buch geschenkt.", "Lui mi ha regalato un libro.",
  "Wir haben zusammen gesungen.", "Abbiamo cantato insieme.",
  "Sie hat gut gekocht.", "Lei ha cucinato bene.",
  "Ich habe die Hausaufgaben vergessen.", "Ho dimenticato i compiti.",
  "Er hat den Brief abgeschickt.", "Lui ha spedito la lettera.",
  "Wir haben im Supermarkt eingekauft.", "Abbiamo fatto la spesa al supermercato.",
  "Sie hat den Termin abgesagt.", "Lei ha annullato l'appuntamento.",
  "Ich habe ihn angerufen.", "L'ho chiamato.",
  "Er hat sich beeilt.", "Si è affrettato.",
  "Wir haben uns verabredet.", "Ci siamo dati appuntamento.",
  "Sie hat gut gespielt.", "Ha giocato bene.",
  "Ich habe die Zeitung gelesen.", "Ho letto il giornale.",
  "Er hat schlecht geschlafen.", "Ha dormito male.",
  "Wir haben im Park spazieren gegangen.", "Abbiamo passeggiato nel parco.",
  "Sie hat die Blumen gegossen.", "Ha innaffiato i fiori.",
  "Ich habe einen Kuchen gebacken.", "Ho fatto una torta.",
  "Er hat sich verspätet.", "È arrivato in ritardo.",
  "Ich habe gestern einen ausgezeichneten Film gesehen.", "Ieri ho visto un film eccellente.",
  "Sie hat kürzlich eine sehr anspruchsvolle Prüfung bestanden.", "Di recente ha superato un esame molto impegnativo.",
  "Er hat vorgestern ein äußerst wichtiges Meeting gehabt.", "L'altro ieri ha avuto una riunione estremamente importante.",
  "Wir haben letzte Woche eine außergewöhnlich interessante Vorlesung besucht.", "La settimana scorsa abbiamo assistito a una lezione straordinariamente interessante.",
  "Ich habe heute Morgen ein sehr nahrhaftes Frühstück gegessen.", "Stamattina ho fatto una colazione molto nutriente.",
  "Sie hat letztes Jahr eine ziemlich anstrengende Reise gemacht.", "L'anno scorso ha fatto un viaggio piuttosto faticoso.",
  "Er hat vorgestern einen äußerst komplizierten Vortrag gehalten.", "L'altro ieri ha tenuto una relazione estremamente complessa.",
  "Wir haben kürzlich ein sehr exklusives Restaurant besucht.", "Recentemente abbiamo visitato un ristorante molto esclusivo.",
  "Ich habe letzte Woche ein ziemlich traditionelles Gericht gekocht.", "La settimana scorsa ho cucinato un piatto piuttosto tradizionale.",
  "Sie hat heute Morgen eine äußerst wichtige E-Mail geschrieben.", "Stamattina ha scritto un'email estremamente importante.",
  "Er hat letzten Monat ein außerordentlich erfolgreiches Projekt abgeschlossen.", "Il mese scorso ha completato un progetto straordinariamente di successo.",
  "Wir haben vorgestern ein sehr interessantes Museum besichtigt.", "L'altro ieri abbiamo visitato un museo molto interessante.",
  "Ich habe letztes Jahr eine ziemlich riskante Investition getätigt.", "L'anno scorso ho effettuato un investimento piuttosto rischioso.",
  "Sie hat kürzlich einen extrem komplizierten Text übersetzt.", "Di recente ha tradotto un testo estremamente complicato.",
  "Er hat letzte Woche eine ungewöhnlich hohe Leistung erbracht.", "La settimana scorsa ha fornito una prestazione insolitamente elevata."
]

const futuroSemplice = [
  "Ich werde morgen früh aufstehen.", "Domani mattina mi alzerò presto.",
  "Wir werden nächste Woche verreisen.", "La settimana prossima partiremo.",
  "Wirst du mir helfen?", "Mi aiuterai?",
  "Ich werde dich anrufen.", "Ti telefonerò.",
  "Sie wird uns besuchen kommen.", "Lei verrà a trovarci.",
  "Wir werden uns bald wiedersehen.", "Ci rivedremo presto.",
  "Ich werde die Prüfung bestehen.", "Supererò l'esame.",
  "Er wird die Reparatur erledigen.", "Lui farà la riparazione.",
  "Wir werden viel Spaß haben.", "Ci divertiremo molto.",
  "Sie wird einen Kuchen backen.", "Lei farà una torta.",
  "Ich werde die Nachricht bekommen.", "Riceverò il messaggio.",
  "Er wird die Arbeit beenden.", "Lui finirà il lavoro.",
  "Wir werden wandern gehen.", "Andremo a fare un'escursione.",
  "Sie werden sich vertragen.", "Loro faranno pace.",
  "Ich werde die Hotelrechnung bezahlen.", "Pagherò il conto dell'albergo.",
  "Er wird den Bus erreichen.", "Lui prenderà l'autobus.",
  "Wir werden im Garten arbeiten.", "Lavoreremo in giardino.",
  "Sie wird sich ausruhen.", "Lei si riposerà.",
  "Ich werde den Hund füttern.", "Darò da mangiare al cane.",
  "Er wird uns einladen.", "Ci inviterà.",
  "Wir werden tanzen.", "Balleremo.",
  "Sie wird das Essen zubereiten.", "Lei preparerà il cibo.",
  "Ich werde die Hausaufgaben machen.", "Farò i compiti.",
  "Er wird den Brief aufgeben.", "Imposterà la lettera.",
  "Wir werden einkaufen gehen.", "Andremo a fare la spesa.",
  "Sie wird den Termin absagen.", "Disdirà l'appuntamento.",
  "Ich werde ihn morgen sehen.", "Lo vedrò domani.",
  "Er wird pünktlich sein.", "Sarà puntuale.",
  "Wir werden uns am Bahnhof treffen.", "Ci incontreremo alla stazione.",
  "Sie wird das Spiel gewinnen.", "Vincerà la partita.",
  "Ich werde in die Bibliothek gehen.", "Andrò in biblioteca.",
  "Er wird gut schlafen.", "Dormirà bene.",
  "Wir werden einen Ausflug machen.", "Faremo una gita.",
  "Sie wird die Pflanzen gießen.", "Annaffierà le piante.",
  "Ich werde einen Kuchen backen.", "Farò una torta.",
  "Er wird sich beeilen.", "Si affretterà.",
  "Morgen werde ich einen sehr anspruchsvollen Test schreiben.", "Domani scriverò un test molto impegnativo.",
  "Sie wird nächste Woche eine äußerst wichtige Präsentation halten.", "La settimana prossima terrà una presentazione estremamente importante.",
  "Er wird heute Abend ein außergewöhnlich raffiniertes Gericht kochen.", "Stasera cucinerà un piatto straordinariamente raffinato.",
  "Wir werden nächsten Monat eine ziemlich riskante Geschäftsentscheidung treffen.", "Il mese prossimo prenderemo una decisione commerciale piuttosto rischiosa.",
  "Ich werde morgen eine äußerst komplizierte Aufgabe erledigen.", "Domani svolgerò un compito estremamente complicato.",
  "Sie wird übermorgen einen sehr exklusiven Laden eröffnen.", "Dopodomani aprirà un negozio molto esclusivo.",
  "Er wird nächste Woche eine ziemlich kontroverse Rede halten.", "La settimana prossima terrà un discorso piuttosto controverso.",
  "Wir werden dieses Jahr eine äußerst ehrgeizige Kampagne starten.", "Quest'anno lanceremo una campagna estremamente ambiziosa.",
  "Ich werde heute eine sehr gedankenanregende Diskussion führen.", "Oggi condurrò una discussione molto stimolante.",
  "Sie wird morgen einen extrem komplexen Vorgang analysieren.", "Domani analizzerà un processo estremamente complesso.",
  "Er wird nächstes Jahr ein außerordentlich innovatives Produkt auf den Markt bringen.", "L'anno prossimo porterà sul mercato un prodotto straordinariamente innovativo.",
  "Wir werden dieses Wochenende eine ziemlich wagemutige Wanderung machen.", "Questo weekend faremo un'escursione piuttosto audace.",
  "Ich werde heute Abend ein sehr raffiniertes Abendessen zubereiten.", "Stasera preparerò una cena molto ricercata.",
  "Sie wird nächsten Monat eine äußerst vielversprechende Geschäftschance wahrnehmen.", "Il mese prossimo coglierà un'opportunità commerciale estremamente promettente."
]

const futuroAnteriore = [
  "Ich werde den Brief geschrieben haben, bis du zurückkommst.", "Avrò scritto la lettera prima che tu ritorni.",
  "Wir werden unsere Koffer gepackt haben, bevor wir zum Flughafen fahren.", "Avremo fatto le valigie prima di andare in aeroporto.",
  "Wirst du deine Hausaufgaben erledigt haben?", "Avrai fatto i compiti?",
  "Ich werde mein Zimmer aufgeräumt haben, wenn du zu Besuch kommst.", "Avrò riordinato la mia camera quando verrai a trovarmi.",
  "Sie wird das Essen gekocht haben, bis wir zurück sind.", "Avrà preparato da mangiare per quando torneremo.",
  "Wir werden getanzt haben, bevor das Fest zu Ende ist.", "Avremo ballato prima che la festa finisca.",
  "Ich werde die Prüfung bestanden haben, wenn die Ergebnisse bekannt gegeben werden.", "Avrò superato l'esame quando verranno comunicati i risultati.",
  "Er wird sein Auto repariert haben, bis nächste Woche.", "Avrà riparato la sua macchina entro la settimana prossima.",
  "Wir werden uns amüsiert haben, nachdem der Film zu Ende ist.", "Ci saremo divertiti dopo che il film sarà finito.",
  "Sie wird den Kuchen gebacken haben, wenn die Gäste ankommen.", "Avrà sfornato la torta quando arriveranno gli ospiti.",
  "Ich werde die E-Mail beantwortet haben, wenn ich ins Büro komme.", "Avrò risposto all'email quando arriverò in ufficio.",
  "Er wird seine Arbeit beendet haben, bis der Chef kommt.", "Avrà finito il lavoro prima che arrivi il capo.",
  "Wir werden alles gesehen haben, wenn wir die Stadt verlassen.", "Avremo visto tutto quando lasceremo la città.",
  "Sie werden ihre Meinungsverschiedenheiten geklärt haben, bis dahin.", "Avranno chiarito i loro diverbi fino ad allora.",
  "Ich werde die Rechnung beglichen haben, bevor ich das Restaurant verlasse.", "Avrò saldato il conto prima di lasciare il ristorante.",
  "Er wird den letzten Bus erreicht haben, wenn er am Bahnhof ankommt.", "Avrà preso l'ultimo autobus quando arriverà alla stazione.",
  "Wir werden den Rasen gemäht haben, bevor es anfängt zu regnen.", "Avremo tagliato l'erba prima che cominci a piovere.",
  "Sie wird sich erholt haben, wenn wir zurückkommen.", "Si sarà riposata quando torneremo.",
  "Ich werde den Hund gefüttert haben, bevor ich das Haus verlasse.", "Avrò dato da mangiare al cane prima di uscire.",
  "Er wird die Gäste empfangen haben, wenn wir ankommen.", "Avrà accolto gli ospiti quando arriveremo.",
  "Wir werden getanzt haben, bevor die Musik aufhört.", "Avremo ballato prima che la musica finisca.",
  "Sie wird alles vorbereitet haben, bis wir da sind.", "Avrà preparato tutto prima che arriviamo.",
  "Ich werde meine Aufgaben erledigt haben, bevor ich schlafen gehe.", "Avrò completato i miei compiti prima di andare a letto.",
  "Er wird den Brief eingeworfen haben, wenn er ins Büro kommt.", "Avrà imbucato la lettera quando arriverà in ufficio.",
  "Wir werden alles gekauft haben, bis der Supermarkt schließt.", "Avremo comprato tutto prima che il supermercato chiuda.",
  "Sie wird den Termin storniert haben, wenn ich sie anrufe.", "Avrà disdetto l'appuntamento quando la chiamerò.",
  "Ich werde ihn getroffen haben, bevor ich abreise.", "Lo avrò incontrato prima di partire.",
  "Er wird angekommen sein, wenn das Meeting beginnt.", "Sarà arrivato quando inizierà la riunione.",
  "Wir werden uns verabredet haben, bis dahin.", "Ci saremo dati appuntamento fino ad allora.",
  "Sie wird gewonnen haben, wenn das Spiel endet.", "Avrà vinto quando la partita finirà.",
  "Ich werde den Artikel gelesen haben, bis wir diskutieren.", "Avrò letto l'articolo prima che ne discutiamo.",
  "Er wird ausgeschlafen haben, wenn wir ihn abholen.", "Avrà dormito bene quando lo andremo a prendere.",
  "Wir werden spazieren gegangen sein, bis es dunkel wird.", "Avremo fatto una passeggiata prima che si faccia buio.",
  "Sie wird die Blumen gegossen haben, wenn ich nach Hause komme.", "Avrà annaffiato i fiori quando tornerò a casa.",
  "Ich werde den Kuchen zubereitet haben, bis die Gäste ankommen.", "Avrò preparato la torta prima che arrivino gli ospiti.",
  "Er wird pünktlich gewesen sein, wenn das Meeting beginnt.", "Sarà stato puntuale quando inizierà la riunione.",
  "Ich werde meinen Bericht fertiggeschrieben haben, bevor die Frist abläuft.", "Avrò scritto la mia relazione prima che scada il termine.",
  "Sie wird den Vertrag unterzeichnet haben, bevor die Verhandlungen beginnen.", "Avrà firmato il contratto prima che inizino i negoziati.",
  "Er wird dasEssen zubereitet haben, bis die Gäste eintreffen.", "Avrà preparato da mangiare per quando arriveranno gli ospiti.",
  "Wir werden unsere Ausbildung abgeschlossen haben, wenn das Jahr endet.", "Avremo completato la nostra formazione quando finirà l'anno.",
  "Ich werde mein Projekt beendet haben, bis zur Präsentation nächste Woche.", "Avrò terminato il mio progetto prima della presentazione della settimana prossima.",
  "Sie wird den Umzug erledigt haben, bevor das Studium losgeht.", "Avrà effettuato il trasloco prima dell'inizio dell'università.",
  "Er wird seinen Vortrag vorbereitet haben, bis die Konferenz beginnt.", "Avrà preparato la sua relazione prima dell'inizio della conferenza.",
  "Wir werden die Renovierung abgeschlossen haben, bis ihr zu Besuch kommt.", "Avremo completato la ristrutturazione per quando verrete a trovarci.",
  "Ich werde mein Buch gelesen haben, bis wir diskutieren.", "Avrò letto il mio libro prima che ne discutiamo.",
  "Sie wird den Jahresabschluss fertig haben, wenn das Geschäftsjahr endet.", "Avrà completato il bilancio quando finirà l'esercizio finanziario.",
  "Er wird seine Ausbildung beendet haben, wenn die Stelle ausgeschrieben wird.", "Avrà terminato la sua formazione quando il posto sarà bandito.",
  "Wir werden unsere Pläne ausgearbeitet haben, bis wir uns wieder treffen.", "Avremo elaborato i nostri piani per quando ci rincontreremo.",
  "Ich werde meine Prüfungen bestanden haben, bis die Ferien beginnen.", "Avrò superato i miei esami prima dell'inizio delle vacanze.",
  "Sie wird ihr Studium abgeschlossen haben, wenn sie 30 Jahre alt ist.", "Avrà completato i suoi studi quando avrà 30 anni."
]

const condizionalePresente = [
  "Ich würde dir gerne helfen.", "Ti aiuterei volentieri.",
  "Wir würden gerne nach Italien reisen.", "Ci piacerebbe viaggiare in Italia.",
  "Würdest du mir beim Umzug helfen?", "Mi aiuteresti con il trasloco?",
  "Ich würde dich morgen anrufen.", "Ti telefonerei domani.",
  "Sie würde uns besuchen kommen, wenn sie Zeit hätte.", "Verrà a trovarci, se avesse tempo.",
  "Wir würden uns öfter treffen, wenn wir in der gleichen Stadt wohnen würden.", "Ci incontreremmo più spesso, se abitassimo nella stessa città.",
  "Ich würde die Prüfung bestehen, wenn ich mehr gelernt hätte.", "Supererei l'esame, se avessi studiato di più.",
  "Er würde die Reparatur schneller erledigen, wenn er das richtige Werkzeug hätte.", "Farebbe più velocemente la riparazione, se avesse gli attrezzi giusti.",
  "Wir würden viel Spaß haben, wenn du auch kommen würdest.", "Ci divertiremmo molto, se venissi anche tu.",
  "Sie würde einen größeren Kuchen backen, wenn mehr Gäste kommen würden.", "Farebbe una torta più grande, se venissero più ospiti.",
  "Ich würde die E-Mail sofort beantworten, wenn ich mehr Zeit hätte.", "Risponderei subito alla mail, se avessi più tempo.",
  "Er würde die Arbeit schneller beenden, wenn ihn niemand stören würde.", "Finirebbe prima il lavoro, se nessuno lo disturbasse.",
  "Wir würden länger bleiben, wenn wir könnten.", "Rimarremmo più a lungo, se potessimo.",
  "Sie würden sich vertragen, wenn sie weniger stur wären.", "Farebbero pace, se fossero meno testardi.",
  "Ich würde die Rechnung bezahlen, wenn ich mein Portemonnaie dabei hätte.", "Pagherei il conto, se avessi con me il portafogli.",
  "Er würde den Bus erreichen, wenn er sich mehr beeilen würde.", "Prenderebbe l'autobus, se si sbrigasse di più.",
  "Wir würden im Garten arbeiten, wenn es nicht regnen würde.", "Lavoreremmo in giardino, se non piovesse.",
  "Sie würde sich ausruhen, wenn sie nicht so beschäftigt wäre.", "Si riposerebbe, se non fosse così impegnata.",
  "Ich würde den Hund füttern, aber ich habe kein Futter mehr.", "Darei da mangiare al cane, ma non ho più cibo.",
  "Er würde uns einladen, aber er hat zu wenig Platz.", "Ci inviterebbe, ma non ha abbastanza spazio.",
  "Wir würden tanzen, wenn sie Musik auflegen würde.", "Balleremmo, se lei mettesse musica.",
  "Sie würde das Essen selbst zubereiten, wenn sie mehr Zeit hätte.", "Preparerebbe lei il cibo, se avesse più tempo.",
  "Ich würde die Hausaufgaben machen, aber ich bin zu müde.", "Farei i compiti, ma sono troppo stanco.",
  "Er würde den Brief persönlich aufgeben, wenn die Post in der Nähe wäre.", "Imposterebbe di persona la lettera, se le poste fossero vicine.",
  "Wir würden mehr einkaufen, wenn wir mehr Geld hätten.", "Compreremmo di più, se avessimo più soldi.",
  "Sie würde den Termin absagen, aber es ist zu kurzfristig.", "Disdirebbe l'appuntamento, ma è troppo a ridosso.",
  "Ich würde ihn morgen besuchen, aber ich muss arbeiten.", "Gli farei visita domani, ma devo lavorare.",
  "Er würde pünktlicher sein, wenn er früher aufstehen würde.", "Sarebbe più puntuale, se si alzasse prima.",
  "Wir würden uns woanders treffen, wenn hier zu viel los wäre.", "Ci incontreremmo da un'altra parte, se qui ci fosse troppa confusione.",
  "Sie würde das Spiel gewinnen, wenn sie mehr trainieren würde.", "Vincerebbe la partita, se si allenasse di più.",
  "Ich würde die Bücher zurückbringen, wenn die Bibliothek nicht schon geschlossen hätte.", "Riporterei i libri, se la biblioteca non fosse già chiusa.",
  "Er würde besser schlafen, wenn nebenan nicht so viel Lärm wäre.", "Dormirebbe meglio, se di fianco non ci fosse tanto rumore.",
  "Wir würden einen Ausflug machen, wenn wir mehr Zeit hätten.", "Faremmo una gita, se avessimo più tempo.",
  "Sie würde die Pflanzen öfter gießen, wenn sie zu Hause wäre.", "Annaffierebbe più spesso le piante, se fosse a casa.",
  "Ich würde einen Kuchen backen, wenn ich die Zutaten dafür hätte.", "Farei una torta, se avessi gli ingredienti necessari.",
  "Er würde sich mehr beeilen, wenn er nicht so müde wäre.", "Si affretterebbe di più, se non fosse così stanco.",
  "Ich würde diesen äußerst komplizierten Text übersetzen.", "Tradurrei questo testo estremamente complicato.",
  "Sie würde diese außergewöhnlich riskante Aufgabe ablehnen.", "Rifiuterebbe questo compito straordinariamente rischioso.",
  "Er würde dieses äußerst wertvolle Kunstwerk kaufen.", "Acquisterebbe quest'opera d'arte estremamente preziosa.",
  "Wir würden diese ziemlich kontroverse Theorie nicht unterstützen.", "Non sosterremmo questa teoria piuttosto controversa.",
  "Ich würde diesen sehr anspruchsvollen Job annehmen.", "Accetterei questo lavoro molto impegnativo.",
  "Sie würde diese überaus komplizierte Situation meistern.", "Gestirebbe questa situazione estremamente complicata.",
  "Er würde dieses außerordentlich profitable Geschäft machen.", "Effettuerebbe quest'affare estremamente redditizio.",
  "Wir würden dieses äußerst ehrgeizige Projekt in Angriff nehmen.", "Intraprenderemmo questo progetto estremamente ambizioso.",
  "Ich würde diese ziemlich provokante Rede nicht halten.", "Non terrei questo discorso piuttosto provocatorio.",
  "Sie würde diese sehr riskante Operation nicht durchführen.", "Non eseguirebbe questo intervento molto rischioso.",
  "Er würde diesen extrem komplexen Text nicht verfassen.", "Non scriverebbe questo testo estremamente complesso.",
  "Wir würden dieses höchst fragile Objekt nicht transportieren.", "Non trasporteremmo questo oggetto altamente fragile.",
  "Ich würde diesen äußerst seltenen Schmetterling nicht fangen.", "Non catturerei questa farfalla estremamente rara.",
  "Sie würde diese überaus wertvolle Violine nicht verkaufen.", "Non venderebbe questo violino estremamente prezioso.",
  "Er würde diese äußerst kontroverse Theorie nicht aufstellen.", "Non porrebbe questa teoria estremamente controversa."
]

const condizionalePassato = [
  "Ich hätte dir gestern geholfen, wenn du mich gefragt hättest.", "Ti avrei aiutato ieri, se me lo avessi chiesto.",
  "Wir wären letztes Jahr nach Italien gereist, wenn wir mehr Zeit gehabt hätten.", "Saremmo andati in Italia l'anno scorso, se avessimo avuto più tempo.",
  "Hättest du mir beim Umzug geholfen, wenn ich dich darum gebeten hätte?", "Mi avresti aiutato con il trasloco, se te l'avessi chiesto?",
  "Ich hätte dich angerufen, aber ich hatte deine Nummer nicht.", "Ti avrei telefonato, ma non avevo il tuo numero.",
  "Sie wäre uns besuchen gekommen, wenn sie nicht krank gewesen wäre.", "Sarebbe venuta a trovarci, se non fosse stata malata.",
  "Wir hätten uns öfter getroffen, wenn wir früher von der gegenseitigen Sympathie gewusst hätten.", "Ci saremmo incontrati più spesso, se avessimo saputo prima della reciproca simpatia.",
  "Ich hätte die Prüfung bestanden, wenn ich mehr Zeit zum Lernen gehabt hätte.", "Avrei superato l'esame, se avessi avuto più tempo per studiare.",
  "Er hätte die Reparatur schneller erledigt, wenn er die Ersatzteile gehabt hätte.", "Avrebbe finito prima la riparazione, se avesse avuto i pezzi di ricambio.",
  "Wir hätten mehr Spaß gehabt, wenn das Wetter besser gewesen wäre.", "Ci saremmo divertiti di più, se il tempo fosse stato migliore.",
  "Sie hätte einen größeren Kuchen gebacken, wenn sie mehr Zutaten gehabt hätte.", "Avrebbe fatto una torta più grande, se avesse avuto più ingredienti.",
  "Ich hätte die E-Mail früher beantwortet, wenn ich sie eher gelesen hätte.", "Avrei risposto prima alla mail, se l'avessi letta prima.",
  "Er hätte die Arbeit schneller beendet, wenn ihn niemand unterbrochen hätte.", "Avrebbe finito prima il lavoro, se nessuno lo avesse interrotto.",
  "Wir wären länger geblieben, wenn wir es uns hätten leisten können.", "Saremmo rimasti più a lungo, se ce lo fossimo potuti permettere.",
  "Sie hätten sich vertragen, wenn sie aufeinander zugegangen wären.", "Si sarebbero riappacificati, se si fossero venuti incontro.",
  "Ich hätte die Rechnung bezahlt, wenn ich genug Geld dabei gehabt hätte.", "Avrei pagato il conto, se avessi avuto abbastanza soldi con me.",
  "Er hätte den Bus erreicht, wenn er sich mehr beeilt hätte.", "Avrebbe preso l'autobus, se si fosse sbrigato di più.",
  "Wir hätten im Garten gearbeitet, wenn es nicht geregnet hätte.", "Avremmo lavorato in giardino, se non avesse piovuto.",
  "Sie hätte sich früher ausgeruht, wenn sie den Stress erkannt hätte.", "Si sarebbe riposata prima, se avesse riconosciuto lo stress.",
  "Ich hätte den Hund gefüttert, aber der Futternapf war leer.", "Avrei dato da mangiare al cane, ma la ciotola era vuota.",
  "Er hätte uns eingeladen, aber sein Haus war zu klein.", "Ci avrebbe invitati, ma la sua casa era troppo piccola.",
  "Wir hätten getanzt, wenn die Musikanlage funktioniert hätte.", "Avremmo ballato, se l'impianto stereo avesse funzionato.",
  "Sie hätte das Essen selbst zubereitet, wenn sie die Zutaten gehabt hätte.", "Avrebbe preparato lei il cibo, se avesse avuto gli ingredienti.",
  "Ich hätte die Hausaufgaben gemacht, wenn ich den Text verstanden hätte.", "Avrei fatto i compiti, se avessi capito il testo.",
  "Er hätte den Brief persönlich aufgegeben, wenn er Zeit gehabt hätte.", "Avrebbe impostato di persona la lettera, se avesse avuto tempo.",
  "Wir hätten mehr eingekauft, wenn es mehr Angebote gegeben hätte.", "Avremmo comprato di più, se ci fossero stati più sconti.",
  "Sie hätte den Termin abgesagt, wenn sie früher von dem Konflikt gewusst hätte.", "Avrebbe disdetto l'appuntamento, se avesse saputo prima del conflitto.",
  "Ich hätte ihn gestern besucht, wenn ich es geschafft hätte.", "Sarei andato a trovarlo ieri, se ce l'avessi fatta.",
  "Er wäre pünktlicher gewesen, wenn er den Verkehr einkalkuliert hätte.", "Sarebbe stato più puntuale se avesse calcolato il traffico.",
  "Wir hätten uns woanders getroffen, wenn wir von der Veranstaltung gewusst hätten.", "Ci saremmo incontrati da un'altra parte, se avessimo saputo dell'evento.",
  "Sie hätte das Spiel gewonnen, wenn sie sich mehr angestrengt hätte.", "Avrebbe vinto la partita, se si fosse impegnata di più.",
  "Ich hätte die Bücher zurückgebracht, aber die Bibliothek war schon zu.", "Avrei riportato i libri, ma la biblioteca era già chiusa.",
  "Er hätte besser geschlafen, wenn die Nachbarn leiser gewesen wären.", "Avrebbe dormito meglio, se i vicini fossero stati più silenziosi.",
  "Wir wären verreist, wenn wir uns den Urlaub hätten leisten können.", "Saremmo partiti, se ci fossimo potuti permettere la vacanza.",
  "Sie hätte die Blumen gegossen, wenn sie noch genug Zeit gehabt hätte.", "Avrebbe annaffiato i fiori, se avesse avuto ancora tempo sufficiente.",
  "Ich hätte einen Kuchen gebacken, wenn ich nicht so müde gewesen wäre.", "Avrei preparato una torta, se non fossi stato così stanco.",
  "Er wäre schneller gegangen, wenn er die Eile erkannt hätte.", "Sarebbe andato più veloce, se avesse riconosciuto l'urgenza.",
  "Ich hätte diesen äußerst komplizierten Vertrag nicht unterzeichnet.", "Non avrei firmato questo contratto estremamente complicato.",
  "Sie hätte diese überaus riskante Expedition nicht gemacht.", "Non avrebbe intrapreso questa spedizione estremamente rischiosa.",
  "Er hätte dieses außergewöhnlich wertvolle Gemälde gekauft.", "Avrebbe acquistato questo dipinto straordinariamente prezioso.",
  "Wir hätten diese ziemlich kontroverse Theorie nicht veröffentlicht.", "Non avremmo pubblicato questa teoria piuttosto controversa.",
  "Ich hätte diesen sehr anspruchsvollen Beruf nicht gewählt.", "Non avrei scelto questa professione molto impegnativa.",
  "Sie hätte diese äußerst komplizierte Aufgabe gemeistert.", "Avrebbe portato a termine questo compito estremamente complicato.",
  "Er hätte diese außerordentlich profitable Investition getätigt.", "Avrebbe effettuato questo investimento estremamente redditizio.",
  "Wir hätten dieses überaus ehrgeizige Ziel nicht erreicht.", "Non avremmo raggiunto questo obiettivo estremamente ambizioso.",
  "Ich hätte diese ziemlich provokante Rede gehalten.", "Avrei tenuto questo discorso piuttosto provocatorio.",
  "Sie hätte diese sehr riskante Operation durchgeführt.", "Avrebbe eseguito questo intervento molto rischioso.",
  "Er hätte diesen äußerst komplexen Roman nicht geschrieben.", "Non avrebbe scritto questo romanzo estremamente complesso.",
  "Wir hätten dieses höchst empfindliche Instrument nicht transportiert.", "Non avremmo trasportato questo strumento estremamente delicato.",
  "Ich hätte diesen außergewöhnlich seltenen Vogel nicht fotografiert.", "Non avrei fotografato questo uccello straordinariamente raro.",
  "Sie hätte diese überaus kostbare Vase nicht zerbrochen.", "Non avrebbe rotto questo vaso estremamente prezioso.",
  "Er hätte diese sehr umstrittene Theorie nicht vertreten.", "Non avrebbe sostenuto questa teoria molto controversa."
]

const congiuntivoPresente = [
  "Ich empfehle, dass du dieses Buch liest.", "Consiglio che tu legga questo libro.", 
  "Es ist wichtig, dass wir pünktlich ankommen.", "È importante che noi arriviamo in orario.", 
  "Ich bezweifle, dass sie die Wahrheit sagt.", "Dubito che lei dica la verità.", 
  "Es ist unwahrscheinlich, dass es morgen regnet.", "È improbabile che domani piova.", 
  "Ich schlage vor, dass wir zusammen lernen.", "Propongo che studiamo insieme.", 
  "Es ist von Vorteil, dass du früh aufstehst.", "È vantaggioso che tu ti alzi presto.", 
  "Ich wünsche, dass ihr viel Erfolg habt.", "Auguro che abbiate molto successo.", 
  "Es ist notwendig, dass du deutsch übst.", "È necessario che tu eserciti il tedesco.", 
  "Ich bezweifle, dass er rechtzeitig ankommt.", "Dubito che lui arrivi puntuale.", 
  "Ich empfehle, dass ihr dieses Museum besucht.", "Consiglio che visitiate questo museo.", 
  "Es ist gut, dass wir regelmäßig Sport treiben.", "È bene che facciamo sport regolarmente.", 
  "Ich schlage vor, dass wir zusammen essen gehen.", "Propongo che usciamo a mangiare insieme.", 
  "Es ist unwahrscheinlich, dass sie heute kommt.", "È improbabile che lei venga oggi.", 
  "Ich bezweifle, dass dieses Mittel wirkt.", "Dubito che questo farmaco funzioni.", 
  "Ich empfehle, dass er einen Arzt aufsucht.", "Consiglio che lui vada da un medico.", 
  "Es ist wichtig, dass du dich ausruhst.", "È importante che tu ti riposi.", 
  "Ich wünsche, dass sie glücklich wird.", "Auguro che lei diventi felice.", 
  "Es ist von Vorteil, dass wir früh aufbrechen.", "È vantaggioso che partiamo presto.", 
  "Ich bezweifle, dass dieses Projekt erfolgreich wird.", "Dubito che questo progetto abbia successo.", 
  "Ich schlage vor, dass ihr euch gut vorbereitet.", "Propongo che vi prepariate bene.", 
  "Es ist notwendig, dass wir zusammenarbeiten.", "È necessario che collaboriamo.",
  "Ich empfehle, dass ihr euch beeilen solltet.", "Consiglio che dovreste sbrigarvi.", 
  "Es ist unwahrscheinlich, dass ich komme.", "È improbabile che io venga.", 
  "Ich bezweifle, dass sie sich ändern wird.", "Dubito che lei cambierà.", 
  "Ich wünsche, dass er glücklich ist.", "Auguro che lui sia felice.", 
  "Es ist gut, dass du mir hilfst.", "È bene che tu mi aiuti.", 
  "Ich schlage vor, dass wir uns treffen.", "Propongo che ci incontriamo.", 
  "Es ist wichtig, dass ihr vorsichtig seid.", "È importante che siate prudenti.", 
  "Ich empfehle, dass du dich entspannst.", "Consiglio che tu ti rilassi.", 
  "Es ist von Vorteil, dass ich früh aufstehe.", "È vantaggioso che mi alzi presto.",
  "Ich bezweifle, dass dieses Buch interessant ist.", "Dubito che questo libro sia interessante.", 
  "Ich wünsche, dass ihr Spaß habt.", "Auguro che vi divertiate.",
  "Es ist wichtig, dass du dieses äußerst komplizierte Problem löst.", "È importante che tu risolva questo problema estremamente complicato.",
  "Ich empfehle, dass sie diese überaus riskante Investition meidet.", "Consiglio che lei eviti questo investimento estremamente rischioso.",
  "Es ist gut, dass er so außergewöhnlich hilfsbereit ist.", "È bene che lui sia così straordinariamente disponibile.",
  "Ich bezweifle, dass sie diese ziemlich kontroverse Theorie vertritt.", "Dubito che lei sostenga questa teoria piuttosto controversa.",
  "Es ist unwahrscheinlich, dass wir dieses sehr anspruchsvolle Projekt durchführen.", "È improbabile che noi portiamo a termine questo progetto molto impegnativo.",
  "Ich schlage vor, dass du diese äußerst komplizierte Aufgabe übernimmst.", "Propongo che tu ti assuma questo compito estremamente complicato.",
  "Es ist von Vorteil, dass er so überaus kreativ ist.", "È vantaggioso che lui sia così estremamente creativo.",
  "Ich bezweifle, dass sie dieses äußerst ehrgeizige Ziel erreicht.", "Dubito che lei raggiunga questa meta estremamente ambiziosa.",
  "Es ist gut, dass wir nicht so provokant argumentieren.", "È bene che non argomentiamo in modo così provocatorio.",
  "Ich empfehle, dass ihr dieses sehr riskante Manöver vermeidet.", "Consiglio che evitiate questa manovra molto rischiosa.",
  "Es ist unwahrscheinlich, dass er diesen extrem komplexen Text verfasst.", "È improbabile che lui scriva questo testo estremamente complesso.",
  "Ich wünsche, dass sie diese außerordentlich seltene Blume findet.", "Spero che lei trovi questo fiore straordinariamente raro.",
  "Es ist von Vorteil, dass ich so umsichtig handle.", "È vantaggioso che io agisca con tanta cautela.",
  "Ich bezweifle, dass wir dieses äußerst fragile Objekt bewegen können.", "Dubito che possiamo spostare questo oggetto estremamente fragile."
]

const congiuntivoImperfetto = [
  "Es wäre gut, wenn du früher kämest.", "Sarebbe bene se tu venissi prima.", 
  "Ich hätte gewünscht, dass du mir geholfen hättest.", "Avrei desiderato che tu mi avessi aiutato.", 
  "Wenn ich mehr Zeit hätte, würde ich dieses Buch lesen.", "Se avessi più tempo, leggerei questo libro.", 
  "Sie hätten uns informieren sollen, bevor sie abreisten.", "Avrebbero dovuto informarci prima di partire.", 
  "Ich hätte vorgeschlagen, dass wir zusammen lernen.", "Avrei proposto che studiassimo insieme.", 
  "Wenn ich wüsste, wie man das macht, würde ich es tun.", "Se sapessi come farlo, lo farei.", 
  "Es wäre besser gewesen, wenn ihr früher angekommen wäret.", "Sarebbe stato meglio se foste arrivati prima.", 
  "Ich hätte gedacht, dass sie pünktlich kommt.", "Avrei pensato che lei sarebbe venuta puntuale.", 
  "Wenn das Wetter besser wäre, würden wir picknicken gehen.", "Se il tempo fosse migliore, andremmo a fare un pic-nic.", 
  "Sie hätten uns warnen sollen, bevor sie das taten.", "Avrebbero dovuto avvertirci prima di farlo.", 
  "Ich hätte empfohlen, dass ihr dieses Museum besucht.", "Avrei consigliato che visitaste questo museo.", 
  "Wenn ich Zeit hätte, würde ich ins Kino gehen.", "Se avessi tempo, andrei al cinema.", 
  "Es wäre besser gewesen, wenn du früher aufgestanden wärest.", "Sarebbe stato meglio se ti fossi alzato prima.", 
  "Ich hätte gezweifelt, dass sie die Prüfung besteht.", "Avrei dubitato che lei superasse l'esame.",
  "Wenn das Wetter gut wäre, gingen wir schwimmen.", "Se il tempo fosse bello, andremmo a nuotare.", 
  "Sie hätten uns davon abraten sollen.", "Ci avrebbero dovuto sconsigliare di farlo.", 
  "Ich hätte vorgeschlagen, dass wir zusammen lernen.", "Avrei proposto che studiassimo insieme.", 
  "Wenn ich mehr Geld hätte, würde ich verreisen.", "Se avessi più soldi, viaggerei.",
  "Es wäre besser, wenn du dich vorbereiten würdest.", "Sarebbe meglio se ti preparassi.", 
  "Ich hätte bezweifelt, dass er die Wahrheit sagt.", "Avrei dubitato che dicesse la verità.", 
  "Wenn sie netter wäre, würde ich ihr helfen.", "Se fosse più gentile, l'aiuterei.", 
  "Sie hätten uns warnen müssen, bevor sie das taten.", "Avrebbero dovuto avvertirci prima di farlo.",
  "Ich hätte nie gedacht, dass du so erfolgreich sein würdest.", "Non avrei mai pensato che tu avresti avuto così tanto successo.",
  "Es wäre mir lieber gewesen, wenn ihr etwas früher gekommen wäret.", "Avrei preferito che foste venuti un po' prima.",
  "Wenn ich mehr Geld gehabt hätte, hätte ich eine Weltreise gemacht.", "Se avessi avuto più soldi, avrei fatto un giro del mondo.",
  "Ich hätte mich gefreut, wenn du meine Party besucht hättest.", "Mi sarei rallegrato se tu avessi partecipato alla mia festa.",
  "Es wäre schön gewesen, wenn wir letzten Sommer nach Italien gefahren wären.", "Sarebbe stato bello se fossimo andati in Italia la scorsa estate.",
  "Wenn ich gewusst hätte, dass du kommst, hätte ich ein größeres Essen gekocht.", "Se avessi saputo che venivi, avrei cucinato un pasto più abbondante.",
  "Ich hätte dir empfohlen, dass du dich mehr vorbereitest.", "Ti avrei consigliato di prepararti meglio.",
  "Wenn ich nicht so müde gewesen wäre, hätte ich länger gelernt.", "Se non fossi stato così stanco, avrei studiato di più.",
  "Es wäre besser gewesen, wenn ihr euch vorher informiert hättet.", "Sarebbe stato meglio se vi foste informati prima.",
  "Ich hätte gehofft, dass wir uns wiedersehen würden.", "Avrei sperato che ci saremmo rivisti.",
  "Wenn ich die Adresse gehabt hätte, wäre ich vorbeigekommen.", "Se avessi avuto l'indirizzo, sarei passato.",
  "Ich hätte gewollt, dass du dieses äußerst komplizierte Rätsel löst.", "Avrei voluto che tu risolvessi questo enigma estremamente complicato.",
  "Es wäre besser gewesen, wenn sie diese überaus riskante Expedition vermieden hätte.", "Sarebbe stato meglio se lei avesse evitato questa spedizione estremamente rischiosa.",
  "Ich hätte mich gefreut, wenn er so außergewöhnlich großzügig gewesen wäre.", "Mi sarei rallegrato se lui fosse stato così straordinariamente generoso.",
  "Es wäre klüger gewesen, wenn sie diese ziemlich kontroverse Theorie nicht vertreten hätte.", "Sarebbe stato più saggio se lei non avesse sostenuto questa teoria piuttosto controversa.",
  "Wenn wir mehr Zeit gehabt hätten, hätten wir dieses sehr anspruchsvolle Projekt begonnen.", "Se avessimo avuto più tempo, avremmo intrapreso questo progetto molto impegnativo.",
  "Ich hätte dir empfohlen, dass du diese äußerst komplizierte Aufgabe übernimmst.", "Ti avrei consigliato di assumerti questo compito estremamente complicato.",
  "Wenn er weniger arrogant gewesen wäre, wäre es von Vorteil gewesen.", "Se lui fosse stato meno arrogante, sarebbe stato vantaggioso.",
  "Ich hätte bezweifelt, dass sie dieses äußerst ehrgeizige Ziel erreicht.", "Avrei dubitato che lei raggiungesse questo obiettivo estremamente ambizioso.",
  "Wir hätten diplomatischer argumentieren sollen.", "Avremmo dovuto argomentare in modo più diplomatico.",
  "Ich hätte dir empfohlen, dass du dieses sehr riskante Unternehmen meidest.", "Ti avrei consigliato di evitare questa impresa molto rischiosa.",
  "Er hätte diesen extrem komplexen Text nicht schreiben dürfen.", "Non avrebbe dovuto scrivere questo testo estremamente complesso.",
  "Ich hätte gehofft, dass sie diese außerordentlich seltene Münze findet.", "Avrei sperato che trovasse questa moneta straordinariamente rara."
]

const congiuntivoMix = [
  "Es ist wichtig, dass du regelmäßig Sport treibst.", "È importante che tu faccia sport regolarmente.",
  "Ich empfehle, dass du dieses Buch liest.", "Ti consiglio di leggere questo libro.",
  "Es wäre schön, wenn wir uns wiedersehen könnten.", "Sarebbe bello se ci potessimo rivedere.",
  "Ich bezweifle, dass sie die Prüfung besteht.", "Dubito che lei superi l'esame.",
  "Es ist unwahrscheinlich, dass es morgen schneit.", "È improbabile che domani nevichi.",
  "Ich schlage vor, dass wir zusammen lernen.", "Propongo che studiamo insieme.",
  "Es ist von Vorteil, dass du früh aufstehst.", "È vantaggioso che tu ti alzi presto.",
  "Ich wünsche, dass ihr eine schöne Reise habt.", "Vi auguro che facciate un buon viaggio.",
  "Es ist notwendig, dass du fleißig übst.", "È necessario che tu ti eserciti con diligenza.",
  "Ich bezweifle, dass er die Arbeit rechtzeitig fertig bekommt.", "Dubito che lui finisca il lavoro in tempo.",
  "Ich empfehle, dass ihr dieses Museum besichtigt.", "Vi consiglio di visitare questo museo.",
  "Es ist gut, dass wir uns weiterbilden.", "È bene che ci aggiorniamo.",
  "Ich schlage vor, dass wir zusammen kochen.", "Propongo che cuciniamo insieme.",
  "Es ist unwahrscheinlich, dass sie heute kommt.", "È improbabile che lei venga oggi.",
  "Ich bezweifle, dass dieser Kurs nützlich ist.", "Dubito che questo corso sia utile.",
  "Ich empfehle, dass er einen Experten konsultiert.", "Gli consiglio di consultare un esperto.",
  "Es ist wichtig, dass du auf deine Gesundheit achtest.", "È importante che tu badi alla tua salute.",
  "Ich wünsche, dass sie Erfolg hat.", "Le auguro che abbia successo.",
  "Es ist von Vorteil, dass wir öffentliche Verkehrsmittel benutzen.", "È vantaggioso che usiamo i mezzi pubblici.",
  "Ich bezweifle, dass dieses Geschäft lange überleben wird.", "Dubito che quest'attività sopravviva a lungo.",
  "Ich schlage vor, dass ihr alle Eventualitäten in Betracht zieht.", "Vi propongo di considerare tutte le eventualità.",
  "Es ist notwendig, dass wir zusammenhalten.", "È necessario che restiamo uniti.",
  "Ich empfehle, dass ihr kein Risiko eingeht.", "Vi sconsiglio di correre rischi.",
  "Es ist unwahrscheinlich, dass ich heute komme.", "È improbabile che io venga oggi.",
  "Ich bezweifle, dass sie ihre Meinung ändert.", "Dubito che lei cambi opinione.",
  "Ich wünsche, dass er zufrieden ist.", "Gli auguro di essere soddisfatto.",
  "Es ist gut, dass du mir hilfst.", "È bene che tu mi aiuti.",
  "Ich schlage vor, dass wir in Kontakt bleiben.", "Propongo che restiamo in contatto.",
  "Es ist wichtig, dass ihr auf eure Sicherheit achtet.", "È importante che facciate attenzione alla vostra sicurezza.",
  "Es wäre nett, wenn du mir beim Umzug helfen könntest.", "Sarebbe carino se tu potessi aiutarmi con il trasloco.",
  "Ich hätte lieber, dass ihr pünktlich kommt.", "Preferirei che arrivaste puntuali.",
  "Es ist erforderlich, dass du deine Hausaufgaben machst.", "È necessario che tu faccia i compiti.",
  "Ich bezweifle, dass dieses Gerücht wahr ist.", "Dubito che questa voce sia vera.",
  "Ich empfehle, dass ihr euch gut auf die Prüfung vorbereitet.", "Vi consiglio di prepararvi bene per l'esame.",
  "Es wäre besser gewesen, wenn wir früher losgefahren wären.", "Sarebbe stato meglio se fossimo partiti prima.",
  "Ich wünsche mir, dass ihr Spaß auf der Party habt.", "Spero che vi divertiate alla festa.",
  "Es ist unwahrscheinlich, dass ich meinen Urlaub absagen werde.", "È improbabile che io annulli le mie vacanze.",
  "Ich bezweifle, dass dieser Film mir gefallen wird.", "Dubito che questo film mi piacerà.",
  "Ich empfehle, dass du dich von einem Experten beraten lässt.", "Ti consiglio di farti consigliare da un esperto.",
  "Es wäre besser gewesen, wenn wir uns vorher abgesprochen hätten.", "Sarebbe stato meglio se ci fossimo messi d'accordo prima.",
  "Ich hätte lieber, dass ihr euch beeilen würdet.", "Preferirei che vi sbrigaste.",
  "Es ist unwahrscheinlich, dass ich heute fertig werde.", "È improbabile che finirò oggi.",
  "Ich bezweifle, dass er fähig ist, das zu tun.", "Dubito che lui sia capace di farlo.",
  "Ich wünsche, dass ihr viel Glück habt.", "Vi auguro tanta fortuna."
]