const presente = [
  "Ich lerne Deutsch.",
  "Sto imparando il tedesco.",
  "Du sprichst gut Englisch.",
  "Tu parli bene l'inglese.",
  "Er arbeitet in einem Büro.",
  "Lui lavora in un ufficio.",
  "Sie liest ein Buch.",
  "Lei sta leggendo un libro.",
  "Es regnet draussen.",
  "Fuori sta piovendo.",
  "Wir essen Pizza zum Abendessen.",
  "Mangiamo la pizza per cena.",
  "Ihr fahrt mit dem Zug.",
  "Voi viaggiate in treno.",
  "Sie spielen Fussball im Park.",
  "Loro giocano a calcio al parco.",
  "Ich trinke gerne Kaffee.",
  "Mi piace bere il caffè.",
  "Du singst wunderschön.",
  "Tu canti magnificamente.",
  "Er geht zur Schule.",
  "Lui va a scuola.",
  "Sie tanzen gerne.",
  "Lei ama ballare.",
  "Es schneit im Winter.",
  "In inverno nevica.",
  "Wir spielen Gitarre zusammen.",
  "Suoniamo la chitarra insieme.",
  "Ihr sprecht drei Sprachen.",
  "Parlate tre lingue.",
  "Sie kochen leckeres Essen.",
  "Loro cucinano cibo delizioso.",
  "Ich besuche meine Grosseltern oft.",
  "Spesso visito i miei nonni.",
  "Du machst einen guten Job.",
  "Fai un buon lavoro.",
  "Er liest ein interessantes Buch.",
  "Lui sta leggendo un libro interessante.",
  "Sie mag Tiere.",
  "Lei ama gli animali.",
  "Es gefällt mir hier.",
  "Mi piace qui.",
  "Wir verstehen uns gut.",
  "Ci capiamo bene.",
  "Ihr spielt gerne Videospiele.",
  "Vi piace giocare ai videogiochi.",
  "Sie reisen gerne um die Welt.",
  "A loro piace viaggiare per il mondo.",
  "Ich gehe jeden Tag ins Fitnessstudio.",
  "Vado in palestra tutti i giorni.",
  "Du magst Schokolade.",
  "Ti piace il cioccolato.",
  "Er macht Yoga für die Entspannung.",
  "Lui fa yoga per rilassarsi.",
  "Sie singt im Chor.",
  "Lei canta nel coro.",
  "Es ist sonnig und warm.",
  "È soleggiato e caldo.",
  "Wir spielen gerne Brettspiele.",
  "Ci piace giocare a giochi da tavolo.",
  "Ihr geht ins Kino am Wochenende.",
  "Andate al cinema durante il fine settimana.",
  "Sie lieben es, am Strand zu sein.",
  "A loro piace stare in spiaggia.",
  "Ich koche gerne Pasta.",
  "Mi piace cucinare la pasta.",
  "Du spielst Fussball im Verein.",
  "Tu giochi a calcio in squadra.",
  "Er reist oft geschäftlich.",
  "Lui viaggia spesso per lavoro.",
  "Sie macht Musik mit ihrem Klavier.",
  "Lei fa musica con il suo pianoforte.",
  "Es ist Winter und kalt draussen.",
  "È inverno e fa freddo fuori.",
  "Wir sprechen mehrere Sprachen.",
  "Parliamo più lingue.",
  "Ihr lest gerne Bücher.",
  "Vi piace leggere libri.",
  "Sie spielen im Park mit Freunden.",
  "Giocano al parco con gli amici."
]

const imprefetto = [
  "Früher spielte ich oft Fussball.",
  "Nel passato giocavo spesso a calcio.",
  "Als Kind liebte ich Schokolade.",
  "Da bambino amavo il cioccolato.",
  "Früher las ich viele Bücher.",
  "Nel passato leggevo molti libri.",
  "Im Sommer schwamm ich im Meer.",
  "Nell'estate nuotavo in mare.",
  "Früher besuchte ich oft meine Grosseltern.",
  "Nel passato visitavo spesso i miei nonni.",
  "In meiner Jugend lernte ich Klavier spielen.",
  "Nella mia giovinezza imparavo a suonare il pianoforte.",
  "Früher wohnten wir in einem kleinen Dorf.",
  "Nel passato abitavamo in un piccolo paese.",
  "Als Kind hatte ich eine Katze.",
  "Da bambino avevo un gatto.",
  "In der Vergangenheit reiste ich nach Frankreich.",
  "Nel passato viaggiavo in Francia.",
  "In meiner Kindheit ass ich gerne Eis.",
  "Nella mia infanzia mangiavo volentieri il gelato.",
  "Früher lernte ich Deutsch an der Schule.",
  "Nel passato imparavo il tedesco a scuola.",
  "In meiner Jugendzeit tanzte ich gerne.",
  "Nella mia gioventù ballavo volentieri.",
  "In der Vergangenheit trank ich oft Tee.",
  "Nel passato bevevo spesso il tè.",
  "Als Kind spielte ich mit meinen Geschwistern.",
  "Da bambino giocavo con i miei fratelli e sorelle.",
  "Früher sang ich im Chor.",
  "Nel passato cantavo nel coro.",
  "In meiner Jugendzeit malte ich gerne.",
  "Nella mia giovinezza dipingevo volentieri.",
  "In der Vergangenheit fuhr ich oft Rad.",
  "Nel passato andavo spesso in bicicletta.",
  "Früher schrieb ich Tagebuch.",
  "Nel passato tenevo un diario.",
  "Als Kind mochte ich Märchen.",
  "Da bambino mi piacevano le fiabe.",
  "In meiner Jugend las ich viele Comics.",
  "Nella mia giovinezza leggevo molti fumetti.",
  "In der Vergangenheit sah ich gerne Filme.",
  "Nel passato guardavo volentieri i film.",
  "Als Kind spielte ich Verstecken.",
  "Da bambino giocavo a nascondino.",
  "Früher sammelte ich Briefmarken.",
  "Nel passato collezionavo francobolli.",
  "In meiner Jugendzeit half ich meinen Eltern im Garten.",
  "Nella mia giovinezza aiutavo i miei genitori in giardino.",
  "In der Vergangenheit ass ich oft Pasta.",
  "Nel passato mangiavo spesso la pasta.",
  "Als Kind hatte ich Angst vor Dunkelheit.",
  "Da bambino avevo paura del buio.",
  "In meiner Jugendzeit spielte ich Basketball.",
  "Nella mia gioventù giocavo a pallacanestro.",
  "Früher machte ich oft Ausflüge in die Natur.",
  "Nel passato facevo spesso escursioni nella natura.",
  "Als Kind fand ich Märchen spannend.",
  "Da bambino trovavo le fiabe affascinanti.",
  "In meiner Jugend las ich viele Bücher.",
  "Nella mia giovinezza leggevo molti libri.",
  "In der Vergangenheit sah ich oft die Sterne am Himmel.",
  "Nel passato guardavo spesso le stelle nel cielo.",
  "Als Kind spielte ich mit Puppen.",
  "Da bambino giocavo con le bambole."
]

const passatoProssimo = [
  "Ich habe gestern Fussball gespielt.",
  "Ho giocato a calcio ieri.",
  "Ich habe Schokolade gegessen.",
  "Ho mangiato cioccolato.",
  "Wir haben letzte Woche viele Bücher gelesen.",
  "Abbiamo letto molti libri la scorsa settimana.",
  "Er hat gestern im Meer geschwommen.",
  "Ha nuotato in mare ieri.",
  "Sie hat ihre Grosseltern besucht.",
  "Ha visitato i suoi nonni.",
  "Ich habe vorhin Klavier gespielt.",
  "Ho suonato il pianoforte poco fa.",
  "Wir haben früher in einem kleinen Dorf gewohnt.",
  "Abitavamo in un piccolo paese in passato.",
  "Sie hat als Kind eine Katze gehabt.",
  "Aveva un gatto da bambina.",
  "Ich habe letzten Sommer nach Frankreich gereist.",
  "Ho viaggiato in Francia l'estate scorsa.",
  "Als Kind habe ich gerne Eis gegessen.",
  "Da bambino mi piaceva mangiare il gelato.",
  "Wir haben Deutsch in der Schule gelernt.",
  "Abbiamo imparato il tedesco a scuola.",
  "In meiner Jugend habe ich gerne getanzt.",
  "Da giovane ballavo volentieri.",
  "Er hat gestern Tee getrunken.",
  "Ha bevuto tè ieri.",
  "Wir haben früher oft Verstecken gespielt.",
  "Giochiamo spesso a nascondino in passato.",
  "Sie hat früher im Chor gesungen.",
  "Cantava nel coro in passato.",
  "Ich habe früher gerne gemalt.",
  "Mi piaceva dipingere in passato.",
  "Wir haben oft Rad gefahren.",
  "Abbiamo spesso fatto una passeggiata in bicicletta.",
  "Er hat gestern Tagebuch geschrieben.",
  "Ha scritto nel diario ieri.",
  "Als Kind mochte ich Märchen.",
  "Da bambino mi piacevano le fiabe.",
  "Wir haben früher viele Comics gelesen.",
  "Leggevamo molti fumetti in passato.",
  "Sie hat gerne Filme geschaut.",
  "Guardava volentieri i film.",
  "Wir haben früher Verstecken gespielt.",
  "Giochiamo spesso a nascondino in passato.",
  "Er hat früher Briefmarken gesammelt.",
  "Raccoglieva francobolli in passato.",
  "Wir haben unseren Eltern im Garten geholfen.",
  "Aiutavamo i nostri genitori in giardino.",
  "Sie hat früher oft Pasta gegessen.",
  "Mangava spesso la pasta in passato.",
  "Ich hatte als Kind Angst vor Dunkelheit.",
  "Avevo paura del buio da bambino.",
  "Wir haben früher Basketball gespielt.",
  "Giochiamo spesso a pallacanestro in passato.",
  "Er hat früher oft Ausflüge in die Natur gemacht.",
  "Faceva spesso escursioni nella natura in passato.",
  "Sie hat Märchen immer spannend gefunden.",
  "Trovava le fiabe sempre affascinanti.",
  "Wir haben früher viele Bücher gelesen.",
  "Leggevamo molti libri in passato.",
  "Er hat oft die Sterne am Himmel angeschaut.",
  "Guardava spesso le stelle nel cielo.",
  "Als Kind habe ich gerne mit Puppen gespielt.",
  "Da bambino giocavo volentieri con le bambole."
]

const futuroSemplice = [
  "Morgen werde ich Italienisch lernen.",
  "Domani imparerò l'italiano.",
  "Nächstes Jahr werden wir verreisen.",
  "L'anno prossimo viaggeremo.",
  "Bald werde ich meine Familie besuchen.",
  "Presto visiterò la mia famiglia.",
  "In der Zukunft werde ich eine neue Sprache lernen.",
  "In futuro imparerò una nuova lingua.",
  "Nächste Woche werden wir eine Party veranstalten.",
  "La settimana prossima organizzeremo una festa.",
  "In ein paar Jahren werde ich um die Welt reisen.",
  "Tra qualche anno viaggerò in giro per il mondo.",
  "Bald werde ich eine neue Karriere beginnen.",
  "Presto inizierò una nuova carriera.",
  "Im nächsten Jahr werden wir ein neues Haus kaufen.",
  "L'anno prossimo compreremo una nuova casa.",
  "In Zukunft werde ich meine Ziele erreichen.",
  "In futuro raggiungerò i miei obiettivi.",
  "In ein paar Jahren werden wir eine Familie gründen.",
  "Tra qualche anno formeremo una famiglia.",
  "Bald werde ich meine Träume verwirklichen.",
  "Presto realizzerò i miei sogni.",
  "In Zukunft werden wir technologische Fortschritte sehen.",
  "In futuro vedremo progressi tecnologici.",
  "Nächstes Jahr werde ich meinen Geburtstag feiern.",
  "L'anno prossimo festeggerò il mio compleanno.",
  "In Zukunft werden wir erneuerbare Energien nutzen.",
  "In futuro utilizzeremo energie rinnovabili.",
  "Bald werde ich eine Weltreise machen.",
  "Presto farò un viaggio intorno al mondo.",
  "Im nächsten Jahr werden wir viele Abenteuer erleben.",
  "L'anno prossimo vivremo molte avventure.",
  "In Zukunft werden wir mehr Zeit für uns haben.",
  "In futuro avremo più tempo per noi stessi.",
  "Bald werde ich meine Fähigkeiten verbessern.",
  "Presto migliorerò le mie abilità.",
  "In ein paar Jahren werden wir unsere Ziele erreichen.",
  "Tra qualche anno raggiungeremo i nostri obiettivi.",
  "In Zukunft werden wir die Welt besser verstehen.",
  "In futuro comprenderemo meglio il mondo.",
  "Nächste Woche werde ich meine Prüfung bestehen.",
  "La settimana prossima passerò il mio esame.",
  "In der Zukunft werden wir mehr über das Universum lernen.",
  "In futuro impareremo di più sull'universo.",
  "Bald werde ich einen neuen Job finden.",
  "Presto troverò un nuovo lavoro.",
  "In Zukunft werden wir mehr für den Umweltschutz tun.",
  "In futuro faremo di più per la protezione dell'ambiente.",
  "Nächstes Jahr werde ich eine neue Wohnung mieten.",
  "L'anno prossimo affitterò un nuovo appartamento.",
  "In Zukunft werden wir bessere Kommunikationsmittel haben.",
  "In futuro avremo migliori mezzi di comunicazione.",
  "Bald werde ich meine Ausbildung abschliessen.",
  "Presto concluderò la mia formazione.",
  "In Zukunft werden wir erneuerbare Energien wichtiger finden.",
  "In futuro daremo più importanza alle energie rinnovabili.",
  "Nächste Woche werde ich einen Kurs belegen.",
  "La settimana prossima frequenterò un corso.",
  "In der Zukunft werden wir mehr über die Geschichte lernen.",
  "In futuro impareremo di più sulla storia.",
  "Bald werde ich ein erfolgreiches Projekt abschliessen.",
  "Presto terminerò con successo un progetto.",
  "In Zukunft werden wir bessere Bildungsmöglichkeiten haben.",
  "In futuro avremo migliori opportunità educative.",
  "Nächstes Jahr werde ich einen Marathon laufen.",
  "L'anno prossimo correrò una maratona.",
  "In Zukunft werden wir bessere Gesundheitsversorgung haben.",
  "In futuro avremo migliori servizi sanitari.",
  "Bald werde ich ein Buch veröffentlichen.",
  "Presto pubblicherò un libro.",
  "In Zukunft werden wir mehr über die Natur erfahren.",
  "In futuro scopriremo di più sulla natura.",
  "Nächstes Jahr werde ich meinen Führerschein machen.",
  "L'anno prossimo prenderò la patente.",
  "In der Zukunft werden wir umweltfreundlicher leben.",
  "In futuro vivremo in modo più ecologico.",
  "Bald werde ich meine Kreativität ausleben.",
  "Presto esprimerò la mia creatività.",
  "In Zukunft werden wir bessere Möglichkeiten haben.",
  "In futuro avremo migliori opportunità."
]

const futuroAnteriore = [
  "Bis morgen werde ich meine Hausaufgaben gemacht haben.",
  "Entro domani avrò fatto i compiti.",
  "Bis nächste Woche werden wir das Projekt abgeschlossen haben.",
  "Entro la prossima settimana avremo completato il progetto.",
  "Bis zum nächsten Monat werde ich Italienisch gelernt haben.",
  "Entro il prossimo mese avrò imparato l'italiano.",
  "Bis nächstes Jahr werden sie einen neuen Job gefunden haben.",
  "Entro l'anno prossimo avranno trovato un nuovo lavoro.",
  "Bis zum nächsten Sommer werden wir viele Reisen unternommen haben.",
  "Entro la prossima estate avremo fatto molti viaggi.",
  "Bis nächste Woche werden sie die Prüfung bestanden haben.",
  "Entro la prossima settimana avranno superato l'esame.",
  "Bis zum nächsten Jahr werden wir unser Haus verkauft haben.",
  "Entro l'anno prossimo avremo venduto la nostra casa.",
  "Bis morgen werden sie die Entscheidung getroffen haben.",
  "Entro domani avranno preso la decisione.",
  "Bis nächste Woche werde ich den Bericht geschrieben haben.",
  "Entro la prossima settimana avrò scritto la relazione.",
  "Bis nächstes Jahr werden wir das Problem gelöst haben.",
  "Entro l'anno prossimo avremo risolto il problema.",
  "Bis zum nächsten Monat werde ich meine Familie besucht haben.",
  "Entro il prossimo mese avrò visitato la mia famiglia.",
  "Bis zum nächsten Sommer werden sie eine neue Wohnung gekauft haben.",
  "Entro la prossima estate avranno comprato un nuovo appartamento.",
  "Bis morgen werden wir die Reservierung vorgenommen haben.",
  "Entro domani avremo effettuato la prenotazione.",
  "Bis nächste Woche werde ich die Präsentation vorbereitet haben.",
  "Entro la prossima settimana avrò preparato la presentazione.",
  "Bis zum nächsten Monat werden sie das Ziel erreicht haben.",
  "Entro il prossimo mese avranno raggiunto l'obiettivo.",
  "Bis zum nächsten Jahr werde ich meinen Führerschein gemacht haben.",
  "Entro l'anno prossimo avrò preso la patente.",
  "Bis zum nächsten Sommer werden sie eine neue Sprache gelernt haben.",
  "Entro la prossima estate avranno imparato una nuova lingua.",
  "Bis morgen werde ich mein Handy repariert haben.",
  "Entro domani avrò riparato il mio telefono.",
  "Bis nächste Woche werden sie das Buch gelesen haben.",
  "Entro la prossima settimana avranno letto il libro.",
  "Bis zum nächsten Monat werde ich meinen Freund getroffen haben.",
  "Entro il prossimo mese avrò incontrato il mio amico.",
  "Bis nächstes Jahr werden sie ihre Ziele erreicht haben.",
  "Entro l'anno prossimo avranno raggiunto i loro obiettivi.",
  "Bis zum nächsten Sommer werden wir die Entscheidung getroffen haben.",
  "Entro la prossima estate avremo preso la decisione.",
  "Bis morgen werde ich die Reise gebucht haben.",
  "Entro domani avrò prenotato il viaggio.",
  "Bis nächste Woche werden sie das Problem gelöst haben.",
  "Entro la prossima settimana avranno risolto il problema.",
  "Bis zum nächsten Monat werde ich meine Ausbildung abgeschlossen haben.",
  "Entro il prossimo mese avrò completato la mia formazione.",
  "Bis nächstes Jahr werden sie ein neues Auto gekauft haben.",
  "Entro l'anno prossimo avranno comprato una nuova macchina.",
  "Bis zum nächsten Sommer werden wir den Vertrag unterzeichnet haben.",
  "Entro la prossima estate avremo firmato il contratto.",
  "Bis morgen werde ich die Lösung gefunden haben.",
  "Entro domani avrò trovato la soluzione.",
  "Bis nächste Woche werden sie ihre Pläne gemacht haben.",
  "Entro la prossima settimana avranno fatto i loro piani.",
  "Bis nächstes Jahr werde ich das Buch geschrieben haben.",
  "Entro l'anno prossimo avrò scritto il libro.",
  "Bis zum nächsten Monat werden sie die Antwort bekommen haben.",
  "Entro il prossimo mese avranno ricevuto la risposta.",
  "Bis zum nächsten Sommer werden wir das Ziel erreicht haben.",
  "Entro la prossima estate avremo raggiunto l'obiettivo.",
  "Bis morgen werde ich meinen Freund getroffen haben.",
  "Entro domani avrò incontrato il mio amico.",
  "Bis nächste Woche werden sie ihre Träume verwirklicht haben.",
  "Entro la prossima settimana avranno realizzato i loro sogni.",
  "Bis nächstes Jahr werden wir unsere Entscheidung getroffen haben.",
  "Entro l'anno prossimo avremo preso la nostra decisione.",
  "Bis zum nächsten Sommer werden sie das Projekt abgeschlossen haben.",
  "Entro la prossima estate avranno completato il progetto."
]

const condizionalePresente = [
  "Ich würde gerne nach Italien reisen.",
  "Mi piacerebbe viaggiare in Italia.",
  "Ich würde gerne eine neue Sprache lernen.",
  "Mi piacerebbe imparare una nuova lingua.",
  "Wenn ich Zeit hätte, würde ich ein Buch lesen.",
  "Se avessi tempo, leggerei un libro.",
  "Ich würde gerne mehr Sport treiben.",
  "Mi piacerebbe fare più sport.",
  "Wenn ich viel Geld hätte, würde ich ein Haus kaufen.",
  "Se avessi molti soldi, comprerei una casa.",
  "Ich würde gerne mehr Zeit mit meiner Familie verbringen.",
  "Mi piacerebbe passare più tempo con la mia famiglia.",
  "Wenn ich mehr Erfahrung hätte, würde ich mich bewerben.",
  "Se avessi più esperienza, farei domanda.",
  "Ich würde gerne besser kochen können.",
  "Mi piacerebbe saper cucinare meglio.",
  "Wenn ich morgen frei hätte, würde ich verreisen.",
  "Se domani avessi libero, partirei.",
  "Ich würde gerne ein Musikinstrument spielen können.",
  "Mi piacerebbe saper suonare uno strumento musicale.",
  "Wenn ich die Möglichkeit hätte, würde ich ins Ausland gehen.",
  "Se avessi l'opportunità, andrei all'estero.",
  "Ich würde gerne einen Film sehen.",
  "Mi piacerebbe vedere un film.",
  "Wenn ich mehr Zeit hätte, würde ich einen Sprachkurs besuchen.",
  "Se avessi più tempo, frequenterei un corso di lingua.",
  "Ich würde gerne mehr reisen.",
  "Mi piacerebbe viaggiare di più.",
  "Wenn ich weniger Arbeit hätte, würde ich mehr entspannen.",
  "Se avessi meno lavoro, mi rilasserei di più.",
  "Ich würde gerne mehr Bücher lesen.",
  "Mi piacerebbe leggere più libri.",
  "Wenn ich reich wäre, würde ich wohltätige Zwecke unterstützen.",
  "Se fossi ricco, sosterrei cause benefiche.",
  "Ich würde gerne bessere Noten bekommen.",
  "Mi piacerebbe ottenere voti migliori.",
  "Wenn ich mehr Zeit hätte, würde ich ein Hobby entwickeln.",
  "Se avessi più tempo, coltiverei un hobby.",
  "Ich würde gerne mehr Zeit in der Natur verbringen.",
  "Mi piacerebbe passare più tempo nella natura.",
  "Wenn ich im Lotto gewinnen würde, würde ich reisen.",
  "Se vincessi alla lotteria, viaggerei.",
  "Ich würde gerne meine Fremdsprachenkenntnisse verbessern.",
  "Mi piacerebbe migliorare le mie competenze linguistiche.",
  "Wenn ich berühmt wäre, würde ich meine Fans treffen.",
  "Se fossi famoso, incontrerei i miei fan.",
  "Ich würde gerne mehr Zeit mit meinen Freunden verbringen.",
  "Mi piacerebbe passare più tempo con i miei amici.",
  "Wenn ich mehr Energie hätte, würde ich mehr unternehmen.",
  "Se avessi più energia, farei più cose.",
  "Ich würde gerne einen guten Job finden.",
  "Mi piacerebbe trovare un buon lavoro.",
  "Wenn ich mehr Geld hätte, würde ich sparen.",
  "Se avessi più soldi, risparmierei.",
  "Ich würde gerne mehr Zeit für meine Hobbys haben.",
  "Mi piacerebbe avere più tempo per i miei hobby.",
  "Wenn ich eine Sprachreise machen würde, würde ich meine Sprachkenntnisse verbessern.",
  "Se facessi un viaggio linguistico, migliorerei le mie competenze linguistiche.",
  "Ich würde gerne mehr über andere Kulturen erfahren.",
  "Mi piacerebbe scoprire di più sulle altre culture.",
  "Wenn ich mehr Geduld hätte, würde ich weniger gestresst sein.",
  "Se avessi più pazienza, sarei meno stressato.",
  "Ich würde gerne ein neues Hobby ausprobieren.",
  "Mi piacerebbe provare un nuovo hobby.",
  "Wenn ich mehr Zeit hätte, würde ich ein Instrument lernen.",
  "Se avessi più tempo, imparerei a suonare uno strumento.",
  "Ich würde gerne mehr Zeit in der Natur verbringen.",
  "Mi piacerebbe passare più tempo nella natura.",
  "Wenn ich mehr Geld hätte, würde ich reisen.",
  "Se avessi più soldi, viaggerei.",
  "Ich würde gerne mehr Sport treiben.",
  "Mi piacerebbe fare più sport.",
  "Wenn ich berühmt wäre, würde ich meine Fans treffen.",
  "Se fossi famoso, incontrerei i miei fan.",
  "Ich würde gerne mehr über Geschichte lernen.",
  "Mi piacerebbe imparare di più sulla storia.",
  "Wenn ich im Lotto gewinnen würde, würde ich ein Haus kaufen.",
  "Se vincessi alla lotteria, comprerei una casa.",
  "Ich würde gerne einen guten Job finden.",
  "Mi piacerebbe trovare un buon lavoro.",
  "Wenn ich mehr Zeit hätte, würde ich ein Buch lesen.",
  "Se avessi più tempo, leggerei un libro."
]

const condizionalePassato = [
  "Wenn ich Zeit gehabt hätte, wäre ich ins Kino gegangen.",
  "Se avessi avuto tempo, sarei andato al cinema.",
  "Sie hätten mir eine E-Mail geschickt, wenn sie meine Adresse gehabt hätten.",
  "Mi avrebbero mandato una e-mail se avessero avuto il mio indirizzo.",
  "Wenn er das Geld gehabt hätte, hätte er das Buch gekauft.",
  "Se avesse avuto i soldi, avrebbe comprato il libro.",
  "Wenn wir früher gekommen wären, hätten wir noch einen Tisch bekommen.",
  "Se fossimo arrivati prima, avremmo avuto ancora un tavolo.",
  "Er hätte den Zug verpasst, wenn du ihn nicht geweckt hättest.",
  "Avrebbe perso il treno se tu non l'avessi svegliato.",
  "Wenn sie das Rezept gehabt hätte, hätte sie den Kuchen gebacken.",
  "Se avesse avuto la ricetta, avrebbe fatto la torta.",
  "Ich hätte dir geholfen, wenn du mich darum gebeten hättest.",
  "Ti avrei aiutato se me lo avessi chiesto.",
  "Wenn es nicht geregnet hätte, wären wir spazieren gegangen.",
  "Se non avesse piovuto, saremmo andati a fare una passeggiata.",
  "Er hätte das Auto repariert, wenn er das Werkzeug gehabt hätte.",
  "Avrebbe riparato la macchina se avesse avuto gli attrezzi.",
  "Wenn sie ihn gesehen hätte, hätte sie mit ihm gesprochen.",
  "Se lo avesse visto, avrebbe parlato con lui.",
  "Er hätte den Job bekommen, wenn er besser vorbereitet gewesen wäre.",
  "Avrebbe ottenuto il lavoro se fosse stato più preparato.",
  "Wenn sie die Chance gehabt hätte, hätte sie ins Ausland gereist.",
  "Se avesse avuto l'opportunità, sarebbe viaggiata all'estero.",
  "Wenn ich gewusst hätte, dass du kommst, hätte ich einen Kuchen gebacken.",
  "Se avessi saputo che venivi, avrei fatto una torta.",
  "Er hätte das Spiel gewonnen, wenn er nicht verletzt gewesen wäre.",
  "Avrebbe vinto la partita se non fosse stato ferito.",
  "Wenn sie mich gefragt hätte, hätte ich ihr geholfen.",
  "Se mi avesse chiesto, l'avrei aiutata.",
  "Wenn ich das Geld gehabt hätte, hätte ich das Geschenk gekauft.",
  "Se avessi avuto i soldi, avrei comprato il regalo.",
  "Sie hätte den Flug verpasst, wenn der Zug Verspätung gehabt hätte.",
  "Avrebbe perso il volo se il treno avesse avuto ritardo.",
  "Wenn wir ihn nicht eingeladen hätten, wäre er nicht gekommen.",
  "Se non l'avessimo invitato, non sarebbe venuto.",
  "Er hätte den Anruf beantwortet, wenn er das Telefon gehabt hätte.",
  "Avrebbe risposto alla chiamata se avesse avuto il telefono.",
  "Wenn sie mehr Zeit gehabt hätte, hätte sie das Buch gelesen.",
  "Se avesse avuto più tempo, avrebbe letto il libro.",
  "Sie hätte den Kuchen gebacken, wenn sie das Rezept gehabt hätte.",
  "Avrebbe fatto la torta se avesse avuto la ricetta.",
  "Wenn er aufmerksamer gewesen wäre, hätte er den Fehler bemerkt.",
  "Se fosse stato più attento, avrebbe notato l'errore.",
  "Wenn sie den Bus verpasst hätte, hätte sie ein Taxi genommen.",
  "Se avesse perso l'autobus, avrebbe preso un taxi.",
  "Wenn wir das früher gewusst hätten, hätten wir uns beeilt.",
  "Se avessimo saputo prima, ci saremmo affrettati.",
  "Er hätte den Job bekommen, wenn er das Interview besser gemacht hätte.",
  "Avrebbe ottenuto il lavoro se avesse fatto meglio il colloquio.",
  "Wenn sie die Sprache besser gesprochen hätte, hätte sie sich verständigen können.",
  "Se avesse parlato meglio la lingua, avrebbe potuto comunicare.",
  "Wenn ich den Zug verpasst hätte, hätte ich den nächsten genommen.",
  "Se avessi perso il treno, avrei preso il prossimo.",
  "Sie hätte die Aufgabe erledigt, wenn sie mehr Zeit gehabt hätte.",
  "Avrebbe completato il compito se avesse avuto più tempo.",
  "Wenn er nicht so müde gewesen wäre, hätte er weitergearbeitet.",
  "Se non fosse stato così stanco, avrebbe continuato a lavorare.",
  "Wenn sie ihn nicht gekannt hätte, hätte sie ihm nicht vertraut.",
  "Se non lo avesse conosciuto, non gli avrebbe dato fiducia.",
  "Wenn ich dich nicht gesehen hätte, hätte ich dich nicht erkannt.",
  "Se non ti avessi visto, non ti avrei riconosciuto.",
  "Wenn sie das gewusst hätte, hätte sie anders reagiert.",
  "Se lo avesse saputo, avrebbe reagito diversamente.",
  "Wenn er das Geld gehabt hätte, hätte er das Haus gekauft.",
  "Se avesse avuto i soldi, avrebbe comprato la casa.",
  "Sie hätte ihn angerufen, wenn sie seine Nummer gehabt hätte.",
  "Lo avrebbe chiamato se avesse avuto il suo numero.",
  "Wenn wir mehr Zeit gehabt hätten, hätten wir länger geblieben.",
  "Se avessimo avuto più tempo, saremmo rimasti più a lungo.",
  "Er hätte den Job bekommen, wenn er besser qualifiziert gewesen wäre.",
  "Avrebbe ottenuto il lavoro se fosse stato più qualificato.",
  "Wenn sie die Chance gehabt hätte, hätte sie ins Ausland studiert.",
  "Se avesse avuto l'opportunità, avrebbe studiato all'estero.",
  "Wenn ich gewusst hätte, dass du kommst, hätte ich ein Geschenk vorbereitet.",
  "Se avessi saputo che venivi, avrei preparato un regalo.",
  "Er hätte das Spiel gewonnen, wenn er schneller gewesen wäre.",
  "Avrebbe vinto la partita se fosse stato più veloce.",
  "Wenn sie mich gebeten hätte, hätte ich ihr geholfen.",
  "Se mi avesse chiesto, l'avrei aiutata.",
  "Wenn ich das Geld gehabt hätte, hätte ich das Buch gekauft.",
  "Se avessi avuto i soldi, avrei comprato il libro."
]